## template: jinja
#cloud-config

# TODO: Maybe run GitHub action and auto replace it on forks?
{% set username = 'ther1d' %} # Replace with your GitHub username

# This is my main cloud-init config that I use for almost all my VMs.
# The config expects Debian/Ubuntu cloud images.

# Hostname and timezone
hostname: Invoker
timezone: Europe/Prague

# SSH hardening
ssh_pwauth: false
disable_root: true

# User configuration
users:
  - name: {{ username }}
    groups: [sudo, adm, docker, video, input, plugdev, netdev] # Add user to necessary groups
    shell: /usr/bin/zsh # Set ZSH as default shell
    lock_passwd: false # Allow password authentication initially
    plain_text_passwd: asd
    # For some reason this fails to set SSH key, most likely network is not up yet at that point.
    # We will set is using runcmd.
    # ssh_import_id:
      # - gh:{{ username }} # Replace with your GitHub username

# Package installation
packages:
  - qemu-guest-agent
  - git
  - neovim
  - zsh
  - python3
  - python3-pip
  - pipx
  - curl
  - wget
  - htop
  - build-essential

# Write ZSH configuration (write as root; chown later)
write_files:
  - path: /home/{{ username }}/.zshrc
    permissions: '0644'
    content: |
      # Load secrets
      # ssh user@1.1.1.1 'cat >> ~/.env' < os.env
      if [ -f ~/.env ]; then
        set -a
        source ~/.env
        set +a
      fi

      # History settings
      HISTFILE=~/.zsh_history
      HISTSIZE=1000
      SAVEHIST=10000
      setopt APPEND_HISTORY

      # Enable VIM mode
      bindkey -v

      # Unbind CTRL+L (later will be used for sgpt completion)
      bindkey -r '^L'

      # Fix not working backspace in VIM insert mode
      bindkey -M viins '^?' backward-delete-char
      bindkey -M viins '^H' backward-delete-char

      # Keep default CTRL+R working
      bindkey -M vicmd '^R' history-incremental-search-backward
      bindkey -M viins '^R' history-incremental-search-backward

      # CTRL+T to attach or create tmux session
      bindkey -s '^T' 'tmux attach || tmux new\n'

      # Add Python packages to PATH
      export PATH="$HOME/.local/bin:$PATH"

      # Custom prompt
      PROMPT='🌕 '

      # Enable completions
      autoload -Uz compinit
      compinit

  # CTRL+C to copy and CTRL+V to paste in nvim.
  - path: /home/{{ username }}/.config/nvim/init.vim
    permissions: '0644'
    content: |
      vnoremap <C-c> "+y
      nnoremap <C-v> "+p
      inoremap <C-v> <C-r>+

  - path: /home/{{ username }}/.config/tmux/tmux.conf
    permissions: '0644'
    content: |
      # Hide bar
      set -g status off

      # Prefix + i launch popup window with sgpt
      bind i display-popup -E -d "#{pane_current_path}" "zsh -c 'source ~/.zshrc && sgpt --repl temp'"

      # VIM like pane navigation
      bind h select-pane -L
      bind j select-pane -D
      bind k select-pane -U
      bind l select-pane -R

# Run commands after initial setup
runcmd:
  - chown -R {{ username }}:{{ username }} /home/{{ username }}
  - su - {{ username }} -c 'pipx install shell-gpt'
  - timeout 3 systemctl enable --now qemu-guest-agent
  # Set public SSH key gh:username should be replaced.
  - sudo -Hu {{ username }} ssh-import-id gh:{{ username }}

final_message: "Cloud-init setup is complete."