#cloud-config

# This is my main cloud-init config that I use for almost all my VMs.
# The config expects Debian/Ubuntu cloud images.

# Hostname and timezone
hostname: Invoker
timezone: Europe/Prague

# SSH hardening
ssh_pwauth: false
disable_root: true

# User configuration
users:
  - name: ther1d
    groups: [sudo, adm, docker, video, input, plugdev, netdev] # Add user to necessary groups
    shell: /usr/bin/zsh # Set ZSH as default shell
    lock_passwd: false # Allow password authentication initially
    plain_text_passwd: asd
    # For some reason this fails to set SSH key, most likely network is not up yet at that point.
    # We will set is using runcmd.
    # ssh_import_id:
      # - gh:ther1d # Replace with your GitHub username
      # This should call https://github.com/<user>.keys
      # TODO: Maybe run GitHub action and auto replace it on forks?

# Package installation
packages:
  - qemu-guest-agent
  - git
  - neovim
  - zsh
  - python3
  - python3-pip
  - pipx
  - curl
  - wget
  - htop
  - build-essential

# Write ZSH configuration (write as root; chown later)
write_files:
  - path: /etc/ssh/sshd_config.d/accept_env.conf
    permissions: '0644'
    content: |
      AcceptEnv OP_SERVICE_ACCOUNT_TOKEN

  - path: /home/ther1d/.zshrc
    permissions: '0644'
    content: |
      # Check if OP_SERVICE_ACCOUNT_TOKEN is set and ~/.env does not exist
      # Can be triggered by running: 
      # OP_SERVICE_ACCOUNT_TOKEN="$(op read 'op://...')" ssh -o SendEnv=OP_SERVICE_ACCOUNT_TOKEN user@host
      if [ "$OP_SERVICE_ACCOUNT_TOKEN" ] && [ ! -f ~/.env ]; then
        # Run in subshell to avoid poluting user environment with
        (
          set -e          # Fail if any command fails
          set -o pipefail # Fail if any command in pipeline fails
          # Inject ENVs using template and passwords from op
          op read 'op://Homelab/.env/notes' | op inject > ~/.env
          # Expected note:
          # VARIABLE_NAME=op://Vault/Item/Field
          # ANOTHER_VARIABLE_NAME=op://Homelab/API Key/password
        )
      fi

      # Load secrets
      if [ -f ~/.env ]; then
        set -a
        source ~/.env
        set +a
      fi

      # History settings
      HISTFILE=~/.zsh_history
      HISTSIZE=1000
      SAVEHIST=10000
      setopt APPEND_HISTORY

      # Enable VIM mode
      bindkey -v

      # Unbind CTRL+L (later will be used for sgpt completion)
      bindkey -r '^L'

      # Fix not working backspace in VIM insert mode
      bindkey -M viins '^?' backward-delete-char
      bindkey -M viins '^H' backward-delete-char

      # Keep default CTRL+R working
      bindkey -M vicmd '^R' history-incremental-search-backward
      bindkey -M viins '^R' history-incremental-search-backward

      # CTRL+T to attach or create tmux session
      bindkey -s '^T' 'tmux attach || tmux new\n'

      # Add Python packages to PATH
      export PATH="$HOME/.local/bin:$PATH"

      # Custom prompt
      PROMPT='🌕 '

      # Enable completions
      autoload -Uz compinit
      compinit

  # CTRL+C to copy and CTRL+V to paste in nvim.
  - path: /home/ther1d/.config/nvim/init.vim
    permissions: '0644'
    content: |
      vnoremap <C-c> "+y
      nnoremap <C-v> "+p
      inoremap <C-v> <C-r>+

  - path: /home/ther1d/.config/tmux/tmux.conf
    permissions: '0644'
    content: |
      # Hide bar
      set -g status off

      # Prefix + i launch popup window with sgpt
      bind i display-popup -E -d "#{pane_current_path}" "zsh -c 'source ~/.zshrc && sgpt --repl temp'"

      # VIM like pane navigation
      bind h select-pane -L
      bind j select-pane -D
      bind k select-pane -U
      bind l select-pane -R

# Run commands after initial setup
runcmd:
  - chown -R ther1d:ther1d /home/ther1d
  - wget -O /tmp/1password-cli.deb https://downloads.1password.com/linux/debian/amd64/stable/1password-cli-amd64-latest.deb
  - apt-get install -y /tmp/1password-cli.deb
  - su - ther1d -c 'pipx install shell-gpt'
  - timeout 3 systemctl enable --now qemu-guest-agent
  # Set public SSH key gh:username should be replaced.
  - sudo -Hu ther1d ssh-import-id gh:ther1d

final_message: "Cloud-init setup is complete."